
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Label Output;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Entry Input;

	private global::Gtk.ToggleButton Compute;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Calculette");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.Output = new global::Gtk.Label();
		this.Output.Name = "Output";
		this.Output.Xalign = 0F;
		this.Output.LabelProp = "";
		this.vbox1.Add(this.Output);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.Output]));
		w1.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Input = new global::Gtk.Entry();
		this.Input.CanFocus = true;
		this.Input.Name = "Input";
		this.Input.IsEditable = true;
		this.Input.InvisibleChar = '●';
		this.hbox1.Add(this.Input);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Input]));
		w2.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Compute = new global::Gtk.ToggleButton();
		this.Compute.CanFocus = true;
		this.Compute.Name = "Compute";
		this.Compute.UseUnderline = true;
		this.Compute.Active = true;
		this.Compute.Label = global::Mono.Unix.Catalog.GetString("Compute");
		this.hbox1.Add(this.Compute);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Compute]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.Compute.Toggled += new global::System.EventHandler(this.OnComputeToggled);
	}
}
